version: '3.3'

services:

  frontend:
    image: node:20.9.0
    volumes:
      - './frontend:/usr'
    command: >
      sh -c "
        npm install && 
        npm run build && 
        npm start
      "
    depends_on:
      - backend

  backend:
    image: amazoncorretto:21
    command: sh -c "java -jar DietiDeals24-backend-0.0.1-SNAPSHOT.jar"
    volumes:
      - './backend/target:/jarfiles'
    working_dir: "/jarfiles"
    depends_on:
      - database
      - cache

  database:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: milleteschi
      POSTGRES_DB: dietideals24
    volumes:
      -  ./database/scheme.sql:/docker-entrypoint-initdb.d/init.sql
    command: ["postgres", "-p", "5433"]
      
  cache:
    image: redis:latest
